// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SyntraWestCSharpTaak4EntityFrameworkOlenaArtiushenko.Models;

namespace SyntraWestCSharpTaak4EntityFrameworkOlenaArtiushenko.Migrations
{
    [DbContext(typeof(GezinContext))]
    [Migration("20210117175229_VoegHobbyPerPersoonToe")]
    partial class VoegHobbyPerPersoonToe
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("SyntraWestCSharpTaak4EntityFrameworkOlenaArtiushenko.Models.Hobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hobby");
                });

            modelBuilder.Entity("SyntraWestCSharpTaak4EntityFrameworkOlenaArtiushenko.Models.HobbyPerPersoon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("HobbyId")
                        .HasColumnType("int");

                    b.Property<int>("PersoonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HobbyId");

                    b.HasIndex("PersoonId");

                    b.ToTable("HobbyPerPersoon");
                });

            modelBuilder.Entity("SyntraWestCSharpTaak4EntityFrameworkOlenaArtiushenko.Models.Huis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("HuisNummer")
                        .HasColumnType("int");

                    b.Property<int>("StraatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StraatId");

                    b.ToTable("Huis");
                });

            modelBuilder.Entity("SyntraWestCSharpTaak4EntityFrameworkOlenaArtiushenko.Models.Persoon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Familienaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Geboortedatum")
                        .HasColumnType("datetime2");

                    b.Property<int>("HuisId")
                        .HasColumnType("int");

                    b.Property<string>("Voornaam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HuisId");

                    b.ToTable("Persoon");
                });

            modelBuilder.Entity("SyntraWestCSharpTaak4EntityFrameworkOlenaArtiushenko.Models.Straat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Straat");
                });

            modelBuilder.Entity("SyntraWestCSharpTaak4EntityFrameworkOlenaArtiushenko.Models.HobbyPerPersoon", b =>
                {
                    b.HasOne("SyntraWestCSharpTaak4EntityFrameworkOlenaArtiushenko.Models.Hobby", "Hobby")
                        .WithMany("HobiesPerPersoon")
                        .HasForeignKey("HobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SyntraWestCSharpTaak4EntityFrameworkOlenaArtiushenko.Models.Persoon", "Persoon")
                        .WithMany("HobiesPerPersoon")
                        .HasForeignKey("PersoonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hobby");

                    b.Navigation("Persoon");
                });

            modelBuilder.Entity("SyntraWestCSharpTaak4EntityFrameworkOlenaArtiushenko.Models.Huis", b =>
                {
                    b.HasOne("SyntraWestCSharpTaak4EntityFrameworkOlenaArtiushenko.Models.Straat", "Straat")
                        .WithMany("Huisen")
                        .HasForeignKey("StraatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Straat");
                });

            modelBuilder.Entity("SyntraWestCSharpTaak4EntityFrameworkOlenaArtiushenko.Models.Persoon", b =>
                {
                    b.HasOne("SyntraWestCSharpTaak4EntityFrameworkOlenaArtiushenko.Models.Huis", "Huis")
                        .WithMany("Personen")
                        .HasForeignKey("HuisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Huis");
                });

            modelBuilder.Entity("SyntraWestCSharpTaak4EntityFrameworkOlenaArtiushenko.Models.Hobby", b =>
                {
                    b.Navigation("HobiesPerPersoon");
                });

            modelBuilder.Entity("SyntraWestCSharpTaak4EntityFrameworkOlenaArtiushenko.Models.Huis", b =>
                {
                    b.Navigation("Personen");
                });

            modelBuilder.Entity("SyntraWestCSharpTaak4EntityFrameworkOlenaArtiushenko.Models.Persoon", b =>
                {
                    b.Navigation("HobiesPerPersoon");
                });

            modelBuilder.Entity("SyntraWestCSharpTaak4EntityFrameworkOlenaArtiushenko.Models.Straat", b =>
                {
                    b.Navigation("Huisen");
                });
#pragma warning restore 612, 618
        }
    }
}
