// <auto-generated />
using System;
using EF2Check.models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EF2Check.Migrations
{
    [DbContext(typeof(Bieren_orgineelContext))]
    [Migration("20210222200315_Add_Persoon_Class")]
    partial class Add_Persoon_Class
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EF2Check.models.Bier", b =>
                {
                    b.Property<int>("BierNr")
                        .HasColumnType("int");

                    b.Property<float?>("Alchohol")
                        .HasColumnType("real");

                    b.Property<string>("BierNaam")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Naam");

                    b.Property<int?>("BrouwerNr")
                        .HasColumnType("int");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<int?>("SoortNr")
                        .HasColumnType("int");

                    b.HasKey("BierNr")
                        .HasName("PK__bieren__F41525D0DC09EB44");

                    b.ToTable("bieren");
                });

            modelBuilder.Entity("EF2Check.models.Brouwer", b =>
                {
                    b.Property<int>("BrouwerNr")
                        .HasColumnType("int");

                    b.Property<string>("Adres")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BrouwerNaam")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Gemeente")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Omzet")
                        .HasColumnType("int");

                    b.Property<int?>("PostCode")
                        .HasColumnType("int");

                    b.HasKey("BrouwerNr")
                        .HasName("PK__brouwers__6FCD96D511A19640");

                    b.ToTable("brouwers");
                });

            modelBuilder.Entity("EF2Check.models.Persoon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FavouriteBierId1")
                        .HasColumnType("int");

                    b.Property<int?>("FavouriteBierId2")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__personnen");

                    b.HasIndex("FavouriteBierId1");

                    b.HasIndex("FavouriteBierId2");

                    b.ToTable("Personnen");
                });

            modelBuilder.Entity("EF2Check.models.Soort", b =>
                {
                    b.Property<int>("SoortNr")
                        .HasColumnType("int");

                    b.Property<string>("SoortNaam")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Soort");

                    b.HasKey("SoortNr")
                        .HasName("PK__soorten__6327B77A02EFC7B8");

                    b.ToTable("soorten");
                });

            modelBuilder.Entity("EF2Check.models.Persoon", b =>
                {
                    b.HasOne("EF2Check.models.Bier", "FavouriteBier1")
                        .WithMany("PplWithBier1")
                        .HasForeignKey("FavouriteBierId1")
                        .HasConstraintName("FK_FavouriteBier1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF2Check.models.Bier", "FavouriteBier2")
                        .WithMany("PplWithBier2")
                        .HasForeignKey("FavouriteBierId2")
                        .HasConstraintName("FK_FavouriteBier2");

                    b.Navigation("FavouriteBier1");

                    b.Navigation("FavouriteBier2");
                });

            modelBuilder.Entity("EF2Check.models.Bier", b =>
                {
                    b.Navigation("PplWithBier1");

                    b.Navigation("PplWithBier2");
                });
#pragma warning restore 612, 618
        }
    }
}
